### ISSUE TITLE
 No compatible USB Bluetooth 4.0 device found!

### ISSUE THREAD

**Issue by andrejlucansky** [mitsuhiko/idasen-control#14]
I get this error when I try to scan for my desk: 

```
C:\Users\andre>idasen-control --scan
Scanning for desks
C:\Users\andre\AppData\Local\Volta\tools\image\packages\idasen-control\node_modules\idasen-control\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:91
    throw new Error('No compatible USB Bluetooth 4.0 device found!');
    ^

Error: No compatible USB Bluetooth 4.0 device found!
    at BluetoothHciSocket.bindUser (C:\Users\andre\AppData\Local\Volta\tools\image\packages\idasen-control\node_modules\idasen-control\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:91:11)
    at BluetoothHciSocket.bindRaw (C:\Users\andre\AppData\Local\Volta\tools\image\packages\idasen-control\node_modules\idasen-control\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:47:8)
    at Hci.init (C:\Users\andre\AppData\Local\Volta\tools\image\packages\idasen-control\node_modules\idasen-control\node_modules\@abandonware\noble\lib\hci-socket\hci.js:120:18)
    at NobleBindings.init (C:\Users\andre\AppData\Local\Volta\tools\image\packages\idasen-control\node_modules\idasen-control\node_modules\@abandonware\noble\lib\hci-socket\bindings.js:93:13)
    at C:\Users\andre\AppData\Local\Volta\tools\image\packages\idasen-control\node_modules\idasen-control\node_modules\@abandonware\noble\lib\noble.js:61:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by mitsuhiko** [comment]
I believe it needs a BLE adapter to work. This project is using the abandonware bluetooth modules. If you believe your adapter should be supported it's probably best to open an issue at their bluetooth repositories (eg: bluetooth-hci-socket)
