### ISSUE TITLE
Windows LIBUSB_ERROR_NOT_SUPPORTED error

### ISSUE THREAD

**Issue by AlexanderMur** [mitsuhiko/idasen-control#4]
Hi!

my Windows version is 1909
when i try to run `idasen-control --scan` i am getting the following error:
```
C:\Users\Alexander>idasen-control --scan
Scanning for desks
C:\Users\Alexander\AppData\Roaming\npm\node_modules\idasen-control\node_modules\usb\usb.js:38
        this.__open()
             ^

Error: LIBUSB_ERROR_NOT_SUPPORTED
    at Device.usb.Device.open (C:\Users\Alexander\AppData\Roaming\npm\node_modules\idasen-control\node_modules\usb\usb.js:38:7)
    at BluetoothHciSocket.bindUser (C:\Users\Alexander\AppData\Roaming\npm\node_modules\idasen-control\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:91:19)
    at BluetoothHciSocket.bindRaw (C:\Users\Alexander\AppData\Roaming\npm\node_modules\idasen-control\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:44:8)
    at Hci.init (C:\Users\Alexander\AppData\Roaming\npm\node_modules\idasen-control\node_modules\@abandonware\noble\lib\hci-socket\hci.js:100:35)
    at NobleBindings.init (C:\Users\Alexander\AppData\Roaming\npm\node_modules\idasen-control\node_modules\@abandonware\noble\lib\hci-socket\bindings.js:78:13)
    at C:\Users\Alexander\AppData\Roaming\npm\node_modules\idasen-control\node_modules\@abandonware\noble\lib\noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: -12
}
```

**Comment by mitsuhiko** [comment]
That unfortunately is an issue of the underlying bluetooth modules.
