### ISSUE TITLE
Error: Cannot find module './build/Release/desktopIdle'

### ISSUE THREAD

**Issue by damog** [mitsuhiko/idasen-control#8]
On a fresh install on Ubuntu:

```
➜  ~ sudo npm install -g idasen-control

/usr/local/bin/idasen-control -> /usr/local/lib/node_modules/idasen-control/src/index.js

> usb@1.6.3 install /usr/local/lib/node_modules/idasen-control/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild


➜  ~ idasen-control --scan
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './build/Release/desktopIdle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/idasen-control/node_modules/desktop-idle/index.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
➜  ~
```

**Comment by zeroarst** [comment]
same here..
